[package]
name = "dijkstra_eventchains"
version = "0.1.0"
edition = "2021"

[dependencies]
colored = "3.0.0"
hashbrown = "*"

[profile.release]
opt-level = 3
lto = true
codegen-units = 1

[profile.bench]
inherits = "release"
